name: Docker Image CI

on:
  []
  # push:
  #   branches: [ "api" ]
  # pull_request:
  #   branches: [ "api" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag mohantnr/aoper:ubuntu_latest
    - name: docker push image
      run: docker push mohantnr/aoper:ubuntu_latest      